# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-28 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(default='', max_length=200)),
                ('Review', models.TextField()),
            ],
        ),
    ]
