# Generated by Django 3.0.3 on 2020-02-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images')),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places='2', max_digits=7)),
            ],
        ),
    ]
